sudo: required
services:
  - docker

before_install:
  - docker build -t svdimchenko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true svdimchenko/react-test npm test

after_success:
  - docker build -t svdimchenko/multi-client ./client
  - docker build -t svdimchenko/multi-nginx ./nginx
  - docker build -t svdimchenko/multi-server ./server
  - docker build -t svdimchenko/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push svdimchenko/multi-client
  - docker push svdimchenko/multi-nginx
  - docker push svdimchenko/multi-server
  - docker push svdimchenko/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-913564465676'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY